name: Test
on:
  pull_request:
    paths: ["go/**/*.go"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - uses: action/setup-go@v5
        with:
          go-version: "1.22"
      - run: go test go/excellent/*.go
