name: Test

on:
  pull_request:
    paths:
      - "go/**/*.go"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Show Go version
        run: go version
        working-directory: go

      - name: Run Go tests
        run: go test ./excellent -v
        working-directory: go
